# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
db.list_collection_names()

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}
fields= {'BusinessName':1, 'scores.Hygiene':1}

score_twenty =establishments.find(query, fields)

# Use count_documents to display the number of documents in the result

count_docs = establishments.count_documents(query)

print("Number of documents in result:", count_docs)


# Display the first document in the results using pprint
pprint(score_twenty[0])

Number of documents in result: 41
{'BusinessName': 'The Chase Rest Home',
 '_id': ObjectId('65ef7d12b029f5df0b971b44'),
 'scores': {'Hygiene': 20}}

In [7]:
# Convert the result to a Pandas DataFrame
hygiene_twenty = pd.DataFrame(list(score_twenty))

# Display the number of rows in the DataFrame

print("Number of rows:", len(hygiene_twenty))

# Display the first 10 rows of the DataFrame
hygiene_twenty.head(10)

Number of rows: 41

                        _id               BusinessName           scores
0  65ef7d12b029f5df0b971b44        The Chase Rest Home  {'Hygiene': 20}
1  65ef7d12b029f5df0b971ec4                 Brenalwood  {'Hygiene': 20}
2  65ef7d12b029f5df0b9721ca              Melrose Hotel  {'Hygiene': 20}
3  65ef7d12b029f5df0b9723b9              Seaford Pizza  {'Hygiene': 20}
4  65ef7d12b029f5df0b9723d2              Golden Palace  {'Hygiene': 20}
5  65ef7d12b029f5df0b972d67           Ashby's Butchers  {'Hygiene': 20}
6  65ef7d12b029f5df0b972f88  South Sea Express Cuisine  {'Hygiene': 20}
7  65ef7d12b029f5df0b9744b8              Golden Palace  {'Hygiene': 20}
8  65ef7d12b029f5df0b9748f9             The Tulip Tree  {'Hygiene': 20}
9  65ef7d12b029f5df0b97510b                      F & S  {'Hygiene': 20}

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [8]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'LocalAuthorityName': 
                                {'$regex':'London'},
                                                        'RatingValue': {'$gte': 4}}

field= {'BusinessName': 1, 'LocalAuthorityName':1, 'RatingValue':1}

rating_value_four = establishments.find(query, field)
# Use count_documents to display the number of documents in the result
print(establishments.count_documents(query))

# Display the first document in the results using pprint
pprint(v[0])

33
{'BusinessName': "Charlie's",
 'LocalAuthorityName': 'City of London Corporation',
 'RatingValue': 4,
 '_id': ObjectId('65ef7d12b029f5df0b97355f')}

In [9]:
# Convert the result to a Pandas DataFrame
london_four_star = pd.DataFrame(list(rating_value_four))
# Display the number of rows in the DataFrame
print(len(london_four_star))
# Display the first 10 rows of the DataFrame
london_four_star.head(10)

33

,_id,BusinessName,RatingValue,LocalAuthorityName
0,65ef7d12b029f5df0b97355f,Charlie's,4,City of London Corporation
1,65ef7d12b029f5df0b973883,Mv City Cruises Erasmus,5,City of London Corporation
2,65ef7d12b029f5df0b9743cf,Benfleet Motor Yacht Club,4,City of London Corporation
3,65ef7d12b029f5df0b9751d0,Tilbury Seafarers Centre,5,City of London Corporation
4,65ef7d12b029f5df0b9751d3,Coombs Catering t/a The Lock and Key,5,City of London Corporation
5,65ef7d13b029f5df0b9758d7,Mv Valulla,5,City of London Corporation
6,65ef7d13b029f5df0b9779e7,Tereza Joanne,5,City of London Corporation
7,65ef7d13b029f5df0b977db0,Brick Lane Brews,4,City of London Corporation
8,65ef7d13b029f5df0b977dc8,City Bar & Grill,5,City of London Corporation
9,65ef7d13b029f5df0b977dc9,The Nuance Group (UK) Limited,5,City of London Corporation

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [10]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.490142
longitude = 0.08384

query ={'RatingValue': 5,
         'geocode.latitude': {'$gte': (latitude - degree_search)},
         'geocode.latitude': {'$lte': (latitude + degree_search)},
         'geocode.longitude': {'$gte': (longitude - degree_search)},
         'geocode.longitude': {'$lte': (longitude + degree_search)},
         'scores.Hygiene': {'$ne': None}
         }
sort =  [('scores.Hygiene', 1)]
limit =5

# Print the results

results = list(establishments.find(query).sort(sort).limit(limit))
pprint(results)

[{'AddressLine1': '80-88 Claremont Road',
  'AddressLine2': 'Seaford',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'Clifden House Dementia Care Centre',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4621.062630784395,
  'FHRSID': 174047,
  'LocalAuthorityBusinessID': 'PI/000027871',
  'LocalAuthorityCode': '105',
  'LocalAuthorityEmailAddress': 'ehealth.ldc@lewes-eastbourne.gov.uk',
  'LocalAuthorityName': 'Lewes',
  'LocalAuthorityWebSite': 'http://www.lewes-eastbourne.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN25 2QD',
  'RatingDate': '2021-08-12T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('65ef7d12b029f5df0b972571'),
  'geocode': {'latitude': 50.776112, 'longitude': 0.089886},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/174047',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': 'Marine Parade',
  'AddressLine2': 'Seaford',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'Beachlands Care Home',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4621.072927670872,
  'FHRSID': 173610,
  'LocalAuthorityBusinessID': 'PI/000026322',
  'LocalAuthorityCode': '105',
  'LocalAuthorityEmailAddress': 'ehealth.ldc@lewes-eastbourne.gov.uk',
  'LocalAuthorityName': 'Lewes',
  'LocalAuthorityWebSite': 'http://www.lewes-eastbourne.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN25 2PY',
  'RatingDate': '2021-10-14T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('65ef7d12b029f5df0b972574'),
  'geocode': {'latitude': 50.775392, 'longitude': 0.088903},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/173610',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 5}},
 {'AddressLine1': '11 Station Road',
  'AddressLine2': 'Seaford',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'Ab Fab Rooms',
  'BusinessType': 'Hotel/bed & breakfast/guest house',
  'BusinessTypeID': 7842,
  'ChangesByServerID': 0,
  'Distance': 4621.4698191377975,
  'FHRSID': 173738,
  'LocalAuthorityBusinessID': 'PI/000026802',
  'LocalAuthorityCode': '105',
  'LocalAuthorityEmailAddress': 'ehealth.ldc@lewes-eastbourne.gov.uk',
  'LocalAuthorityName': 'Lewes',
  'LocalAuthorityWebSite': 'http://www.lewes-eastbourne.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN25 2RB',
  'RatingDate': '2021-12-03T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('65ef7d12b029f5df0b9725fb'),
  'geocode': {'latitude': 50.780751, 'longitude': 0.083468},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/173738',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '23 Claremont Road',
  'AddressLine2': 'Seaford',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'Angies Newsagents',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4620.941086507653,
  'FHRSID': 174020,
  'LocalAuthorityBusinessID': 'PI/000027807',
  'LocalAuthorityCode': '105',
  'LocalAuthorityEmailAddress': 'ehealth.ldc@lewes-eastbourne.gov.uk',
  'LocalAuthorityName': 'Lewes',
  'LocalAuthorityWebSite': 'http://www.lewes-eastbourne.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN25 2PF',
  'RatingDate': '2022-01-22T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('65ef7d12b029f5df0b97251e'),
  'geocode': {'latitude': 50.77601, 'longitude': 0.093059},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/174020',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}},
 {'AddressLine1': '29-31 Claremont Road',
  'AddressLine2': 'Seaford',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'Costcutter Claremont',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4620.941086507653,
  'FHRSID': 637054,
  'LocalAuthorityBusinessID': 'PI/000061384',
  'LocalAuthorityCode': '105',
  'LocalAuthorityEmailAddress': 'ehealth.ldc@lewes-eastbourne.gov.uk',
  'LocalAuthorityName': 'Lewes',
  'LocalAuthorityWebSite': 'http://www.lewes-eastbourne.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN25 2PF',
  'RatingDate': '2021-11-18T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('65ef7d12b029f5df0b97251d'),
  'geocode': {'latitude': 50.77601, 'longitude': 0.093059},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/637054',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}}]

In [11]:
# Convert result to Pandas DataFrame
results_df = pd.DataFrame(results)
# Display
results_df

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,65ef7d12b029f5df0b972571,174047,0,PI/000027871,Clifden House Dementia Care Centre,Caring Premises,5,80-88 Claremont Road,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.089886, 'latitude': 50.776112}",,4621.062631,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,65ef7d12b029f5df0b972574,173610,0,PI/000026322,Beachlands Care Home,Caring Premises,5,Marine Parade,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.088903, 'latitude': 50.775392}",,4621.072928,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,65ef7d12b029f5df0b9725fb,173738,0,PI/000026802,Ab Fab Rooms,Hotel/bed & breakfast/guest house,7842,11 Station Road,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.083468, 'latitude': 50.780751}",,4621.469819,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,65ef7d12b029f5df0b97251e,174020,0,PI/000027807,Angies Newsagents,Retailers - other,4613,23 Claremont Road,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.093059, 'latitude': 50.77601}",,4620.941087,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,65ef7d12b029f5df0b97251d,637054,0,PI/000061384,Costcutter Claremont,Retailers - other,4613,29-31 Claremont Road,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.093059, 'latitude': 50.77601}",,4620.941087,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [13]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
match_score = {"$match":{"scores.Hygiene": 0}}
# 2. Groups the matches by Local Authority
group_score = {"$group": {'_id': "$LocalAuthorityName", 'count': { '$sum': 1 }}}
# 3. Sorts the matches from highest to lowest
sort = {'$sort': { 'count': -1 }}

# Print the number of documents in the result
pipeline = [match_score, group_score, sort]

results = list(establishments.aggregate(pipeline))

print("# of documents: ", len(results))

# Print the first 10 results
pprint(results[0:10])

# of documents:  55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [14]:
# Convert the result to a Pandas DataFrame
hygiene_zero = pd.DataFrame(list(results))

# Display the number of rows in the DataFrame
print("Rows in DataFrame: ", len(hygiene_zero))

# Display the first 10 rows of the DataFrame
hygiene_zero.head(10)

Rows in DataFrame:  55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542